name: scss compile/deploy

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install pre-commit
        run: pip install pre-commit

      - name: Run pre-commit hooks
        run: pre-commit run --all-files

  build:
    needs: pre-commit
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Update Submodules
        run: |
          git submodule update --init --recursive
          git submodule foreach git pull origin main

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16"

      - name: Install SCSS Compiler and Bootstrap
        run: |
          cd ops
          npm install

      - name: Compile SCSS
        run: |
          cd ops
          npm run sass

      - name: Bust Cache
        run: |
          cd ops
          npm run cache-busting

      - name: Replace GA_MEASUREMENT_ID in HTML files
        run: find ./ -type f -name "*.html" -exec sed -i 's/GA_MEASUREMENT_ID/${{ secrets.GA_MEASUREMENT_ID }}/g' {} \;

      - name: Archive compiled files
        uses: actions/upload-artifact@v3
        with:
          name: compiled-files
          path: ./

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Download compiled files
        uses: actions/download-artifact@v3
        with:
          name: compiled-files

      - name: Install SSH key
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy to VPS
        run: |
          ssh-keyscan ${{ secrets.SERVER_HOST }} >> ~/.ssh/known_hosts
          rsync -av --delete ./ ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }}:${{ secrets.DEPLOY_PATH }}

      - name: Reload NGINX
        run: |
          ssh ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }} "sudo /usr/sbin/nginx -s reload"
